name       : python-fido2
version    : 0.3.0
release    : 1
source     :
    - https://github.com/Yubico/python-fido2/archive/0.3.0.tar.gz : 8648c3f0e0aa4310ee1b037f538185bad7f9c0c471158c11a20454caaec535d3
license    :
    - Apache-2.0
    - BSD-2-Clause
    - MPL-2.0
component  : programming.python
summary    : Provides library functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures
description: |
    This library aims to support the FIDO U2F and FIDO 2.0 protocols for communicating with a USB authenticator via the Client-to-Authenticator Protocol (CTAP 1 and 2). In addition to this low-level device access, classes defined in the fido2.client implement higher level device operations.
builddeps  :
    - pkgconfig(python3)
    - python-cryptography
    - python-fakefs
    - python-mock
    - python-setuptools
rundeps    :
    - libu2f-host
    - python-cryptography
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
