name       : python-fido2
version    : 1.0.0
release    : 13
source     :
    - https://github.com/Yubico/python-fido2/releases/download/1.0.0/fido2-1.0.0.tar.gz : 2509a4958b666d747fd5754dfa9357da2d81b52edc0ecff75b68cea939154c02
homepage   : https://github.com/Yubico/python-fido2
license    :
    - Apache-2.0
    - BSD-2-Clause
    - MPL-2.0
component  : programming.python
summary    : Provides library functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures
description: |
    This library aims to support the FIDO U2F and FIDO 2.0 protocols for communicating with a USB authenticator via the Client-to-Authenticator Protocol (CTAP 1 and 2). In addition to this low-level device access, classes defined in the fido2.client implement higher level device operations.
builddeps  :
    - pkgconfig(python3)
    - python-cryptography
    - python-fakefs
    - python-mock
rundeps    :
    - libu2f-host
    - python-cryptography
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
