name       : python-fido2
version    : 1.1.1
release    : 15
source     :
    - https://github.com/Yubico/python-fido2/releases/download/1.1.1/fido2-1.1.1.tar.gz : 5dc495ca8c59c1c337383b4b8c314d46b92d5c6fc650e71984c6d7f954079fc3
homepage   : https://github.com/Yubico/python-fido2
license    :
    - Apache-2.0
    - BSD-2-Clause
    - MPL-2.0
component  : programming.python
summary    : Provides library functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures
description: |
    This library aims to support the FIDO U2F and FIDO 2.0 protocols for communicating with a USB authenticator via the Client-to-Authenticator Protocol (CTAP 1 and 2). In addition to this low-level device access, classes defined in the fido2.client implement higher level device operations.
networking : yes
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-cryptography
    - python-fakefs
    - python-installer
    - python-mock
    - python-packaging
    - python-wheel
rundeps    :
    - libu2f-host
    - python-cryptography
    - python-six
environment: |
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
setup      : |
    python3 -m pip install --user poetry
build      : |
    %python3_setup
install    : |
    %python3_install
