name       : python-fido2
version    : 0.8.1
release    : 8
source     :
    - https://github.com/Yubico/python-fido2/releases/download/0.8.1/fido2-0.8.1.tar.gz : 449068f6876f397c8bb96ebc6a75c81c2692f045126d3f13ece21d409acdf7c3
license    :
    - Apache-2.0
    - BSD-2-Clause
    - MPL-2.0
component  : programming.python
summary    : Provides library functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures
description: |
    This library aims to support the FIDO U2F and FIDO 2.0 protocols for communicating with a USB authenticator via the Client-to-Authenticator Protocol (CTAP 1 and 2). In addition to this low-level device access, classes defined in the fido2.client implement higher level device operations.
builddeps  :
    - pkgconfig(python3)
    - python-cryptography
    - python-fakefs
    - python-mock
    - python-setuptools
rundeps    :
    - libu2f-host
    - python-cryptography
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
